package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"main/graph/model"
)

// UserAuth is the resolver for the userAuth field.
func (r *queryResolver) UserAuth(ctx context.Context, email string) (*model.UserAuthResult, error) {
	student := r.DB.AuthUser(email)
	return &model.UserAuthResult{
		Email:        student.Email,
		PasswordHash: student.PasswordHash,
		Role:         &student.Role,
		Version:      &student.Version,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
