// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type UserAuthResult struct {
	Email        string  `json:"email"`
	PasswordHash string  `json:"passwordHash"`
	Role         *string `json:"role,omitempty"`
	Version      *int32  `json:"version,omitempty"`
}
